
sudo: required

services:
  - docker
before_install:
  - gem install bundler --pre
  - docker build -t hanhee/docker-react -f Dockerfile.dev .

script:
  - docker run hanhee/docker-react npm run test -- --coverage